export default {
  smell: "Lena's apartment smells like garlic, rosemary, and something with wine in it.",
  canvases: "Canvases line the walls — unfinished, overlapping, all slightly wild. It's beautiful chaos.",
  you_came: '"You came!" She says it like she wasn\'t entirely sure you would.',
  wine: 'She pours two glasses of red without asking and hands you one. The food is laid out simply and perfectly.',
  choice_art: 'Ask about her art',
  choice_food: 'Compliment the food',
  choice_flirt: 'Flirt boldly — hold her gaze a beat too long',
  art_1: '"Oh — you noticed?" She lights up. Not performed delight. Genuine surprise.',
  art_2: '"I paint what I can\'t say. Which means I paint a lot."',
  art_3: 'You talk about the paintings for an hour. The wine disappears.',
  food_1: '"This is incredible — seriously. What\'s in the sauce?"',
  food_2: '"Wine, shallots, and a pinch of stubbornness."',
  food_3: "She's pleased — quietly, warmly pleased. You eat well and laugh more than you expected.",
  flirt_charm: 'You let the silence stretch half a second too long, holding her eyes with a soft smile.',
  flirt_blush: "Color rises in her cheeks. She looks away first — but she's smiling.",
  flirt_trouble: '"You\'re trouble," she says quietly, like it\'s not entirely a complaint.',
  flirt_fail_1: "You try your best but the moment lands slightly off — a beat too eager.",
  flirt_fail_2: 'Lena smiles politely and refills your glass. The evening stays warm but measured.',
} as const;
