export default {
  smell: "L'appartement de Lena sent l'ail, le romarin, et quelque chose avec du vin.",
  canvases: "Des toiles bordent les murs — inachevees, superposees, toutes un peu sauvages. C'est un beau chaos.",
  you_came: '"Vous etes venu !" Elle le dit comme si elle n\'en etait pas tout a fait sure.',
  wine: "Elle verse deux verres de rouge sans demander et vous en tend un. La nourriture est disposee simplement et parfaitement.",
  choice_art: 'Demander a propos de son art',
  choice_food: 'Complimenter la nourriture',
  choice_flirt: 'Flirter audacieusement — soutenir son regard un peu trop longtemps',
  art_1: '"Oh — vous avez remarque ?" Elle s\'illumine. Pas un ravissement joue. Une vraie surprise.',
  art_2: '"Je peins ce que je ne peux pas dire. Ce qui veut dire que je peins beaucoup."',
  art_3: 'Vous parlez des peintures pendant une heure. Le vin disparait.',
  food_1: '"C\'est incroyable — serieusement. Qu\'est-ce qu\'il y a dans la sauce ?"',
  food_2: '"Du vin, des echalotes, et une pincee d\'obstination."',
  food_3: "Elle est ravie — tranquillement, chaleureusement ravie. Vous mangez bien et riez plus que prevu.",
  flirt_charm: 'Vous laissez le silence s\'etirer une demi-seconde de trop, soutenant son regard avec un doux sourire.',
  flirt_blush: "La couleur monte a ses joues. Elle detourne le regard la premiere — mais elle sourit.",
  flirt_trouble: '"Vous etes un probleme," dit-elle doucement, comme si ce n\'etait pas entierement une plainte.',
  flirt_fail_1: "Vous faites de votre mieux mais le moment tombe un peu a cote — un battement trop empresse.",
  flirt_fail_2: "Lena sourit poliment et remplit votre verre. La soiree reste chaleureuse mais mesuree.",
} as const;
