import type { Plugin } from 'vite';
import { resolve, relative, basename, join } from 'path';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs';

const VIRTUAL_ID = 'vylos:texts';
const RESOLVED_ID = '\0vylos:texts';

/**
 * Vite plugin that merges per-language text files into a single virtual module.
 *
 * Scans:  locations/<loc>/texts/<scope>/<lang>.ts
 *         global/texts/<scope>/<lang>.ts
 *
 * Produces: import texts from 'vylos:texts'
 *           texts.bridge.actions.endShift  → TextEntry
 *           texts.global.actions.openMenu  → TextEntry
 *
 * Also generates vylos-texts.d.ts for IntelliSense.
 */
export function vylosI18nPlugin(projectRoot: string): Plugin {
  // moduleId (e.g. "bridge/actions") → list of lang file absolute paths
  const textModules = new Map<string, string[]>();

  function scanTextDirs() {
    textModules.clear();
    const dirs = [
      { base: resolve(projectRoot, 'locations'), prefix: '' },
      { base: resolve(projectRoot, 'global', 'texts'), prefix: 'global/' },
    ];

    for (const { base, prefix } of dirs) {
      if (!existsSync(base)) continue;

      if (prefix === 'global/') {
        // global/texts/<scope>/<lang>.ts
        for (const scope of safeDirRead(base)) {
          const scopeDir = resolve(base, scope);
          const langs = safeDirRead(scopeDir).filter(f => f.endsWith('.ts'));
          if (langs.length > 0) {
            textModules.set(`global/${scope}`, langs.map(l => resolve(scopeDir, l)));
          }
        }
      } else {
        // locations/<loc>/texts/<scope>/<lang>.ts
        for (const loc of safeDirRead(base)) {
          const textsDir = resolve(base, loc, 'texts');
          if (!existsSync(textsDir)) continue;
          for (const scope of safeDirRead(textsDir)) {
            const scopeDir = resolve(textsDir, scope);
            const langs = safeDirRead(scopeDir).filter(f => f.endsWith('.ts'));
            if (langs.length > 0) {
              textModules.set(`${loc}/${scope}`, langs.map(l => resolve(scopeDir, l)));
            }
          }
        }
      }
    }
  }

  function generateDts() {
    // Build nested tree structure: { bridge: { actions: { endShift: TextEntry } } }
    const tree: Record<string, Record<string, string[]>> = {};

    for (const [moduleId, langFiles] of textModules) {
      const parts = moduleId.split('/');
      const group = parts[0]; // e.g. "bridge" or "global"
      const scope = parts[1]; // e.g. "actions"
      const keys = extractKeys(langFiles[0]);
      if (keys.length === 0) continue;

      if (!tree[group]) tree[group] = {};
      tree[group][scope] = keys;
    }

    const lines: string[] = [
      '// Auto-generated by vylos-i18n plugin — do not edit',
      '// Provides IntelliSense for vylos:texts virtual module',
      '',
      `declare module 'vylos:texts' {`,
      `  import type { TextEntry } from '@vylos/core';`,
      `  const texts: {`,
    ];

    for (const [group, scopes] of Object.entries(tree).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`    readonly ${group}: {`);
      for (const [scope, keys] of Object.entries(scopes).sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`      readonly ${scope}: {`);
        for (const key of keys) {
          lines.push(`        readonly ${key}: TextEntry;`);
        }
        lines.push(`      };`);
      }
      lines.push(`    };`);
    }

    lines.push(`  };`, `  export default texts;`, `}`, ``);

    const dtsPath = join(projectRoot, 'vylos-texts.d.ts');
    const content = lines.join('\n');
    const existing = existsSync(dtsPath) ? readFileSync(dtsPath, 'utf-8') : '';
    if (existing !== content) {
      writeFileSync(dtsPath, content, 'utf-8');
    }
  }

  function generateModuleCode(): string {
    const imports: string[] = [];
    // Track: varName → { group, scope }
    const entries: { varName: string; lang: string; group: string; scope: string }[] = [];
    let idx = 0;

    for (const [moduleId, langFiles] of textModules) {
      const parts = moduleId.split('/');
      const group = parts[0];
      const scope = parts[1];

      for (const filePath of langFiles) {
        const lang = basename(filePath, '.ts');
        const varName = `_i${idx++}`;
        imports.push(`import ${varName} from '${filePath.replace(/\\/g, '/')}';`);
        entries.push({ varName, lang, group, scope });
      }
    }

    // Build nested tree at runtime
    return `${imports.join('\n')}

function _merge(langs) {
  const r = {};
  for (const [lang, entries] of Object.entries(langs)) {
    for (const [key, value] of Object.entries(entries)) {
      if (!r[key]) r[key] = {};
      r[key][lang] = value;
    }
  }
  return r;
}

const _tree = {};
${entries.map(e =>
  `if(!_tree['${e.group}'])_tree['${e.group}']={};` +
  `if(!_tree['${e.group}']['${e.scope}'])_tree['${e.group}']['${e.scope}']={_langs:{}};` +
  `_tree['${e.group}']['${e.scope}']._langs['${e.lang}']=${e.varName};`
).join('\n')}

const _result = {};
for (const [group, scopes] of Object.entries(_tree)) {
  _result[group] = {};
  for (const [scope, data] of Object.entries(scopes)) {
    _result[group][scope] = _merge(data._langs);
  }
}

export default _result;
`;
  }

  return {
    name: 'vylos-i18n',

    buildStart() {
      scanTextDirs();
      generateDts();
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
    },

    load(id) {
      if (id !== RESOLVED_ID) return;
      return generateModuleCode();
    },

    handleHotUpdate({ file }) {
      const rel = relative(projectRoot, file).replace(/\\/g, '/');
      if (rel.includes('/texts/') && file.endsWith('.ts')) {
        scanTextDirs();
        generateDts();
      }
    },
  };
}

function safeDirRead(dir: string): string[] {
  try {
    return readdirSync(dir, { withFileTypes: true })
      .filter(d => d.isDirectory() || d.isFile())
      .map(d => d.name);
  } catch {
    return [];
  }
}

/** Extract exported keys from a text file via regex (no TS compilation needed) */
function extractKeys(filePath: string): string[] {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const keys: string[] = [];
    const re = /^\s*(\w+)\s*:/gm;
    let match: RegExpExecArray | null;
    while ((match = re.exec(content)) !== null) {
      const key = match[1];
      if (key !== 'default' && key !== 'export') {
        keys.push(key);
      }
    }
    return keys;
  } catch {
    return [];
  }
}
