export default {
  walking: 'Maya walks beside you along the river path, jacket over her arm, shoulders finally relaxed.',
  sunset: 'The sunset turns everything gold. She tilts her face toward the light and closes her eyes for a moment.',
  travel: '"I used to want to travel. Open a cafe in Portugal or somewhere ridiculous like that."',
  here: '"Now I\'m not sure. Maybe what I want is already here and I just haven\'t found the right angle on it."',
  glance: 'She glances at you — quick, a little vulnerable.',
  choice_share: 'Share your own dreams with her',
  choice_light: 'Keep it light — joke about Portugal',
  share_1: 'You tell her what you came here chasing. The real version, not the polished one.',
  share_2: 'She listens. Actually listens — not waiting for her turn, just... present.',
  share_3: '"That\'s the most honest thing anyone\'s said to me in a long time."',
  share_4: 'She bumps your shoulder gently. The river keeps moving beneath you both.',
  light_1: '"Portugal has good tiles," you offer. "Terrible for espresso quality control though."',
  light_2: 'She snorts — caught off guard — then laughs properly, leaning into your arm for a second.',
  light_3: '"You\'re a terrible person," she says, grinning. "I mean that fondly."',
} as const;
