export default {
  walking: 'Maya marche a cote de vous le long du chemin de la riviere, veste sur le bras, epaules enfin detendues.',
  sunset: 'Le coucher de soleil rend tout dore. Elle incline le visage vers la lumiere et ferme les yeux un instant.',
  travel: '"Avant, je voulais voyager. Ouvrir un cafe au Portugal ou un truc ridicule comme ca."',
  here: '"Maintenant je ne suis plus sure. Peut-etre que ce que je veux est deja ici et que je n\'ai juste pas trouve le bon angle."',
  glance: 'Elle vous jette un coup d\'oeil — rapide, un peu vulnerable.',
  choice_share: 'Partager vos propres reves avec elle',
  choice_light: 'Rester leger — plaisanter sur le Portugal',
  share_1: 'Vous lui racontez ce que vous etes venu chercher ici. La vraie version, pas la version polie.',
  share_2: "Elle ecoute. Vraiment. Pas en attendant son tour, juste... presente.",
  share_3: '"C\'est la chose la plus honnete que quelqu\'un m\'ait dite depuis longtemps."',
  share_4: 'Elle vous pousse doucement l\'epaule. La riviere continue de couler sous vous deux.',
  light_1: '"Le Portugal a de beaux carrelages," offrez-vous. "Terrible pour le controle qualite de l\'espresso par contre."',
  light_2: "Elle renifle — prise au depourvu — puis rit franchement, s'appuyant contre votre bras une seconde.",
  light_3: '"Vous etes une personne terrible," dit-elle en souriant. "Je le dis affectueusement."',
} as const;
