export default {
  enter: "The hallway is narrow and warmly lit. You've barely stepped out when you hear a thud.",
  groceries: "A paper bag has toppled from someone's arms — groceries scattered across the floor.",
  eggs: '"Oh no, not the eggs..."',
  crouching: "She's crouching to gather things up — dark hair falling over her face, cheeks flushed.",
  choice_help: 'Help her pick everything up',
  choice_hi: 'Just say hi and offer a smile',
  help_1: 'You drop to one knee and start collecting oranges that have rolled to the wall.',
  help_2: '"Oh! Thank you, really — I always carry too much at once."',
  help_3: 'She laughs softly, a little embarrassed, a little grateful.',
  help_4: '"I\'m Lena, by the way. 4B. You must be the new neighbor."',
  hi_1: 'You wave and offer your warmest smile. "Need any help?"',
  hi_2: '"I\'ve got it, but thanks! You\'re sweet."',
  hi_3: '"Lena. 4B. Welcome to the building."',
  farewell: 'You exchange a warm smile before she disappears behind her door.',
} as const;
